"""update_local_listings_peachcars

Revision ID: 95cab13bcd20
Revises: b9142be28358
Create Date: 2026-05-13 11:52:59.802697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cab13bcd20'
down_revision: Union[str, None] = 'b9142be28358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_listings', sa.Column('engine_cc', sa.Integer(), nullable=True))
    op.add_column('local_listings', sa.Column('fuel_type', sa.String(length=20), nullable=True))
    op.add_column('local_listings', sa.Column('transmission', sa.String(length=20), nullable=True))
    op.add_column('local_listings', sa.Column('body_type', sa.String(length=50), nullable=True))
    op.add_column('local_listings', sa.Column('drive_type', sa.String(length=10), nullable=True))
    op.add_column('local_listings', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('local_listings', sa.Column('listing_url', sa.Text(), nullable=True))
    op.add_column('local_listings', sa.Column('images_json', sa.Text(), nullable=True))
    op.alter_column('local_listings', 'source_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
    op.alter_column('local_listings', 'price_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('local_listings', 'condition',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('local_listings', 'condition',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('local_listings', 'price_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('local_listings', 'source_id',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('local_listings', 'images_json')
    op.drop_column('local_listings', 'listing_url')
    op.drop_column('local_listings', 'color')
    op.drop_column('local_listings', 'drive_type')
    op.drop_column('local_listings', 'body_type')
    op.drop_column('local_listings', 'transmission')
    op.drop_column('local_listings', 'fuel_type')
    op.drop_column('local_listings', 'engine_cc')
    # ### end Alembic commands ###
