"""initial_schema

Revision ID: b9142be28358
Revises: 
Create Date: 2026-05-13 09:16:53.828896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9142be28358'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('price_jpy', sa.Float(), nullable=True),
    sa.Column('auction_grade', sa.String(length=10), nullable=True),
    sa.Column('location_jp', sa.String(length=100), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('is_cleaned', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_car_listings_id'), 'car_listings', ['id'], unique=False)
    op.create_index(op.f('ix_car_listings_is_cleaned'), 'car_listings', ['is_cleaned'], unique=False)
    op.create_index(op.f('ix_car_listings_make'), 'car_listings', ['make'], unique=False)
    op.create_index(op.f('ix_car_listings_model'), 'car_listings', ['model'], unique=False)
    op.create_index(op.f('ix_car_listings_price_usd'), 'car_listings', ['price_usd'], unique=False)
    op.create_index(op.f('ix_car_listings_year'), 'car_listings', ['year'], unique=False)
    op.create_index('ix_make_model_year', 'car_listings', ['make', 'model', 'year'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_ccy', sa.String(length=3), nullable=True),
    sa.Column('to_ccy', sa.String(length=3), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('price_kes', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_local_listings_make'), 'local_listings', ['make'], unique=False)
    op.create_index(op.f('ix_local_listings_model'), 'local_listings', ['model'], unique=False)
    op.create_index(op.f('ix_local_listings_price_kes'), 'local_listings', ['price_kes'], unique=False)
    op.create_index(op.f('ix_local_listings_year'), 'local_listings', ['year'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('predicted_usd', sa.Float(), nullable=True),
    sa.Column('actual_usd', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('features_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_cost_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('purchase_usd', sa.Float(), nullable=False),
    sa.Column('shipping_usd', sa.Float(), nullable=True),
    sa.Column('insurance_usd', sa.Float(), nullable=True),
    sa.Column('cif_usd', sa.Float(), nullable=True),
    sa.Column('usd_kes_rate', sa.Float(), nullable=True),
    sa.Column('cif_kes', sa.Float(), nullable=True),
    sa.Column('customs_duty_kes', sa.Float(), nullable=True),
    sa.Column('excise_duty_kes', sa.Float(), nullable=True),
    sa.Column('vat_kes', sa.Float(), nullable=True),
    sa.Column('idf_levy_kes', sa.Float(), nullable=True),
    sa.Column('rdl_levy_kes', sa.Float(), nullable=True),
    sa.Column('port_charges_kes', sa.Float(), nullable=True),
    sa.Column('clearing_kes', sa.Float(), nullable=True),
    sa.Column('ntsa_kes', sa.Float(), nullable=True),
    sa.Column('total_kes', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['car_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_cost_estimates')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_local_listings_year'), table_name='local_listings')
    op.drop_index(op.f('ix_local_listings_price_kes'), table_name='local_listings')
    op.drop_index(op.f('ix_local_listings_model'), table_name='local_listings')
    op.drop_index(op.f('ix_local_listings_make'), table_name='local_listings')
    op.drop_table('local_listings')
    op.drop_table('exchange_rates')
    op.drop_index('ix_make_model_year', table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_year'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_price_usd'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_model'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_make'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_is_cleaned'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_id'), table_name='car_listings')
    op.drop_table('car_listings')
    # ### end Alembic commands ###
